services:
  - type: web
    name: cek-fakta-api
    env: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SERP_API_KEY
        sync: false
